#pragma once
///////////////////////////////////////////////////////////////////////////////
// File: Admin.h
///////////////////////////////////////////////////////////////////////////////
//
// The code in this file is released under the The MIT License (MIT)
//
// Copyright (c) 2018 JetByte Limited.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the “Software”), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
///////////////////////////////////////////////////////////////////////////////

#ifndef JETBYTE_TOOLS_CONFIG_WIN32
#define JETBYTE_TOOLS_CONFIG_WIN32
#endif

#ifdef JETBYTE_SHOW_CONFIG_DETAILS
#ifndef JETBYTE_SHOW_WIN32_CONFIG_DETAILS
#define JETBYTE_SHOW_WIN32_CONFIG_DETAILS JETBYTE_SHOW_CONFIG_DETAILS
#endif
#endif

#ifndef JETBYTE_SHOW_WIN32_CONFIG_DETAILS
#define JETBYTE_SHOW_WIN32_CONFIG_DETAILS 0
#endif

#ifndef JETBYTE_WIN32_CRITICAL_SECTION_USE_STD_THREADING
#define JETBYTE_WIN32_CRITICAL_SECTION_USE_STD_THREADING 0
#endif

#ifndef JETBYTE_BREAK_SEH_EXCEPTION_TRANSLATOR_COMPATABILITY
#define JETBYTE_BREAK_SEH_EXCEPTION_TRANSLATOR_COMPATABILITY 1
#endif

#ifndef JETBYTE_TRANSLATE_SEH_EXCEPTIONS
#define JETBYTE_TRANSLATE_SEH_EXCEPTIONS 1
#endif

#ifndef JETBYTE_TRANSLATE_SEH_EXCEPTIONS_IN_DEBUGGER
#define JETBYTE_TRANSLATE_SEH_EXCEPTIONS_IN_DEBUGGER 1
#endif

#ifndef JETBYTE_EXCEPTION_STACK_TRACES
#define JETBYTE_EXCEPTION_STACK_TRACES 0
#endif

#ifndef JETBYTE_REFERENCE_COUNTED_SMART_POINTER_THROW_ON_NULL_REFERENCE
#define JETBYTE_REFERENCE_COUNTED_SMART_POINTER_THROW_ON_NULL_REFERENCE 0
#endif

#ifndef JETBYTE_REFERENCE_COUNTED_SMART_POINTER_DUMP_ON_NULL_REFERENCE
#define JETBYTE_REFERENCE_COUNTED_SMART_POINTER_DUMP_ON_NULL_REFERENCE 0
#endif

#if (JETBYTE_REFERENCE_COUNTED_SMART_POINTER_DUMP_ON_NULL_REFERENCE == 1)
#if (JETBYTE_REFERENCE_COUNTED_SMART_POINTER_THROW_ON_NULL_REFERENCE == 0)
#error JETBYTE_REFERENCE_COUNTED_SMART_POINTER_DUMP_ON_NULL_REFERENCE requires JETBYTE_REFERENCE_COUNTED_SMART_POINTER_THROW_ON_NULL_REFERENCE
#endif
#endif

#ifndef JETBYTE_SMART_POINTER_THROW_ON_NULL_REFERENCE
#define JETBYTE_SMART_POINTER_THROW_ON_NULL_REFERENCE 0
#endif

#ifndef JETBYTE_SMART_POINTER_DUMP_ON_NULL_REFERENCE
#define JETBYTE_SMART_POINTER_DUMP_ON_NULL_REFERENCE 0
#endif

#if (JETBYTE_SMART_POINTER_DUMP_ON_NULL_REFERENCE == 1)
#if (JETBYTE_SMART_POINTER_THROW_ON_NULL_REFERENCE == 0)
#error JETBYTE_SMART_POINTER_DUMP_ON_NULL_REFERENCE requires JETBYTE_SMART_POINTER_THROW_ON_NULL_REFERENCE
#endif
#endif

#ifndef JETBYTE_PERF_TIMER_QUEUE_MONITORING
#define JETBYTE_PERF_TIMER_QUEUE_MONITORING 1
#endif

#ifndef JETBYTE_PERF_TIMER_CONTENTION_MONITORING
#define JETBYTE_PERF_TIMER_CONTENTION_MONITORING 0
#endif

#ifndef JETBYTE_PERF_TIMER_WHEEL_MONITORING
#define JETBYTE_PERF_TIMER_WHEEL_MONITORING 1
#endif

#ifndef JETBYTE_WIN32_AUTOMATIC_SEH_CRASH_DUMP_CREATION
#define JETBYTE_WIN32_AUTOMATIC_SEH_CRASH_DUMP_CREATION 0
#endif

#ifndef JETBYTE_WIN32_PURE_CALL_CRASH_DUMP_CREATION
#define JETBYTE_WIN32_PURE_CALL_CRASH_DUMP_CREATION 0
#endif

#ifndef JETBYTE_WIN32_DEPRECATE_OPTEX
#define JETBYTE_WIN32_DEPRECATE_OPTEX 1
#endif

#ifndef JETBYTE_WIN32_MINI_DUMP_GENERATOR_BREAK_INTO_DEBUGGER
#define JETBYTE_WIN32_MINI_DUMP_GENERATOR_BREAK_INTO_DEBUGGER 0
#endif

#ifndef JETBYTE_WIN32_DISABLE_MINI_DUMP_CREATION
#define JETBYTE_WIN32_DISABLE_MINI_DUMP_CREATION 0
#endif

#ifndef JETBYTE_WIN32_DISABLE_DEFAULT_MINI_DUMP_CREATION
#define JETBYTE_WIN32_DISABLE_DEFAULT_MINI_DUMP_CREATION 0
#endif

#ifndef JETBYTE_WIN32_CRT_REPORT_HOOK_HANG_ON_ERROR
#define JETBYTE_WIN32_CRT_REPORT_HOOK_HANG_ON_ERROR 0
#endif

#ifndef JETBYTE_WIN32_CRT_REPORT_HOOK_TREAT_ASSERT_AS_WARN
#define JETBYTE_WIN32_CRT_REPORT_HOOK_TREAT_ASSERT_AS_WARN 0
#endif

#ifndef JETBYTE_PURE_CALL_BREAK_INTO_DEBUGGER_IF_PRESENT
#define JETBYTE_PURE_CALL_BREAK_INTO_DEBUGGER_IF_PRESENT 0
#endif

#ifndef JETBYTE_PURE_CALL_BREAK_INTO_DEBUGGER_IF_PRESENT
#define JETBYTE_PURE_CALL_BREAK_INTO_DEBUGGER_IF_PRESENT 0
#endif

#ifndef JETBYTE_PURE_CALL_HANG_ON_ERROR
#define JETBYTE_PURE_CALL_HANG_ON_ERROR 0
#endif

#ifndef JETBYTE_DUMP_NAMED_INDEX_DETAILS_ON_LOCK
#define JETBYTE_DUMP_NAMED_INDEX_DETAILS_ON_LOCK 0
#endif

#ifdef JETBYTE_ADMIN_ENABLE_ALL_THIRD_PARTY_CODE

#ifndef JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER
#define JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER 1
#endif

#else
#ifndef JETBYTE_ADMIN_ENABLE_THIRD_PARTY_CODE
#ifdef JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER
#if (JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER == 1)
#undef JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER
#define JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER 0
#endif
#endif
#endif
#endif

#ifndef JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER
#define JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER 0
#endif

#ifndef JETBYTE_WIN32_DISPLAY_MODULES_DURING_LINKS_TO_CRT_DLL_CHECK
#define JETBYTE_WIN32_DISPLAY_MODULES_DURING_LINKS_TO_CRT_DLL_CHECK 0
#endif

///////////////////////////////////////////////////////////////////////////////
// End of file: Admin.h
///////////////////////////////////////////////////////////////////////////////
