#pragma once
///////////////////////////////////////////////////////////////////////////////
// File: Admin.h
///////////////////////////////////////////////////////////////////////////////
//
// The code in this file is released under the The MIT License (MIT)
//
// Copyright (c) 2018 JetByte Limited.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the “Software”), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
///////////////////////////////////////////////////////////////////////////////

#ifndef JETBYTE_TOOLS_CONFIG_WIN32
#define JETBYTE_TOOLS_CONFIG_WIN32
#endif

#ifdef JETBYTE_SHOW_CONFIG_DETAILS
#ifndef JETBYTE_SHOW_WIN32_CONFIG_DETAILS
#define JETBYTE_SHOW_WIN32_CONFIG_DETAILS JETBYTE_SHOW_CONFIG_DETAILS
#endif
#endif

#ifndef JETBYTE_SHOW_WIN32_CONFIG_DETAILS
#define JETBYTE_SHOW_WIN32_CONFIG_DETAILS 0
#endif

#ifndef JETBYTE_WIN32_CRITICAL_SECTION_USE_STD_THREADING
#define JETBYTE_WIN32_CRITICAL_SECTION_USE_STD_THREADING 0
#endif

#ifndef JETBYTE_BREAK_SEH_EXCEPTION_TRANSLATOR_COMPATABILITY
#define JETBYTE_BREAK_SEH_EXCEPTION_TRANSLATOR_COMPATABILITY 1
#endif

#ifndef JETBYTE_TRANSLATE_SEH_EXCEPTIONS
#define JETBYTE_TRANSLATE_SEH_EXCEPTIONS 1
#endif

#ifndef JETBYTE_TRANSLATE_SEH_EXCEPTIONS_IN_DEBUGGER
#define JETBYTE_TRANSLATE_SEH_EXCEPTIONS_IN_DEBUGGER 1
#endif

#ifndef JETBYTE_EXCEPTION_STACK_TRACES
#define JETBYTE_EXCEPTION_STACK_TRACES 0
#endif

#ifndef JETBYTE_REFERENCE_COUNTED_SMART_POINTER_THROW_ON_NULL_REFERENCE
#define JETBYTE_REFERENCE_COUNTED_SMART_POINTER_THROW_ON_NULL_REFERENCE 0
#endif

#ifndef JETBYTE_REFERENCE_COUNTED_SMART_POINTER_DUMP_ON_NULL_REFERENCE
#define JETBYTE_REFERENCE_COUNTED_SMART_POINTER_DUMP_ON_NULL_REFERENCE 0
#endif

#if (JETBYTE_REFERENCE_COUNTED_SMART_POINTER_DUMP_ON_NULL_REFERENCE == 1)
#if (JETBYTE_REFERENCE_COUNTED_SMART_POINTER_THROW_ON_NULL_REFERENCE == 0)
#error JETBYTE_REFERENCE_COUNTED_SMART_POINTER_DUMP_ON_NULL_REFERENCE requires JETBYTE_REFERENCE_COUNTED_SMART_POINTER_THROW_ON_NULL_REFERENCE
#endif
#endif

#ifndef JETBYTE_SMART_POINTER_THROW_ON_NULL_REFERENCE
#define JETBYTE_SMART_POINTER_THROW_ON_NULL_REFERENCE 0
#endif

#ifndef JETBYTE_SMART_POINTER_DUMP_ON_NULL_REFERENCE
#define JETBYTE_SMART_POINTER_DUMP_ON_NULL_REFERENCE 0
#endif


#if (JETBYTE_SMART_POINTER_DUMP_ON_NULL_REFERENCE == 1)
#if (JETBYTE_SMART_POINTER_THROW_ON_NULL_REFERENCE == 0)
#error JETBYTE_SMART_POINTER_DUMP_ON_NULL_REFERENCE requires JETBYTE_SMART_POINTER_THROW_ON_NULL_REFERENCE
#endif
#endif

#ifndef JETBYTE_PERF_TIMER_QUEUE_MONITORING
#define JETBYTE_PERF_TIMER_QUEUE_MONITORING 1
#endif

#ifndef JETBYTE_PERF_TIMER_CONTENTION_MONITORING
#define JETBYTE_PERF_TIMER_CONTENTION_MONITORING 0
#endif

#ifndef JETBYTE_PERF_TIMER_WHEEL_MONITORING
#define JETBYTE_PERF_TIMER_WHEEL_MONITORING 1
#endif

#ifndef JETBYTE_WIN32_AUTOMATIC_SEH_CRASH_DUMP_CREATION
#define JETBYTE_WIN32_AUTOMATIC_SEH_CRASH_DUMP_CREATION 0
#endif

#ifndef JETBYTE_WIN32_PURE_CALL_CRASH_DUMP_CREATION
#define JETBYTE_WIN32_PURE_CALL_CRASH_DUMP_CREATION 0
#endif


#ifndef JETBYTE_TERMINATE_CRASH_DUMP_CREATION
#define JETBYTE_TERMINATE_CRASH_DUMP_CREATION 0
#endif

#ifndef JETBYTE_UNEXPECTED_CRASH_DUMP_CREATION
#define JETBYTE_UNEXPECTED_CRASH_DUMP_CREATION 0
#endif

#ifndef JETBYTE_WIN32_DEPRECATE_OPTEX
#define JETBYTE_WIN32_DEPRECATE_OPTEX 1
#endif

#ifndef JETBYTE_MINI_DUMP_GENERATOR_BREAK_INTO_DEBUGGER
#define JETBYTE_MINI_DUMP_GENERATOR_BREAK_INTO_DEBUGGER 0
#endif

#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_TERMINATE_HANDLER_ENABLED
#define JETBYTE_GLOBAL_ERROR_HANDLER_TERMINATE_HANDLER_ENABLED 1
#endif

#ifdef _MSVC_LANG
#if _MSVC_LANG > 201402
#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_UNEXPECTED_HANDLER_ENABLED
#define JETBYTE_GLOBAL_ERROR_HANDLER_UNEXPECTED_HANDLER_ENABLED 0
#elif JETBYTE_GLOBAL_ERROR_HANDLER_UNEXPECTED_HANDLER_ENABLED == 1
#error JETBYTE_GLOBAL_ERROR_HANDLER_UNEXPECTED_HANDLER_ENABLED cannot be enabled if C++/17 is being used
#endif
#endif
#endif

#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_UNEXPECTED_HANDLER_ENABLED
#define JETBYTE_GLOBAL_ERROR_HANDLER_UNEXPECTED_HANDLER_ENABLED 1
#endif

#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_NEW_HANDLER_ENABLED
#define JETBYTE_GLOBAL_ERROR_HANDLER_NEW_HANDLER_ENABLED 1
#endif

#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_SIBABRT_HANDLER_ENABLED
#define JETBYTE_GLOBAL_ERROR_HANDLER_SIBABRT_HANDLER_ENABLED 1
#endif

#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_BREAK_IF_DEBUGGER_PRESENT
#define JETBYTE_GLOBAL_ERROR_HANDLER_BREAK_IF_DEBUGGER_PRESENT 1
#endif

#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_SIG_ABORT_CRASH_DUMP_CREATION
#define JETBYTE_GLOBAL_ERROR_HANDLER_SIG_ABORT_CRASH_DUMP_CREATION 1
#endif

#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_HANG_ON_TERMINATE
#define JETBYTE_GLOBAL_ERROR_HANDLER_HANG_ON_TERMINATE 0
#endif

#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_HANG_ON_SIGABRT
#define JETBYTE_GLOBAL_ERROR_HANDLER_HANG_ON_SIGABRT 0
#endif

#ifndef JETBYTE_GLOBAL_ERROR_HANDLER_HANG_ON_UNEXPECTED
#define JETBYTE_GLOBAL_ERROR_HANDLER_HANG_ON_UNEXPECTED 0
#endif

#ifndef JETBYTE_CRT_REPORT_HOOK_HANG_ON_ERROR
#define JETBYTE_CRT_REPORT_HOOK_HANG_ON_ERROR 0
#endif

#ifndef JETBYTE_PURE_CALL_BREAK_INTO_DEBUGGER_IF_PRESENT
#define JETBYTE_PURE_CALL_BREAK_INTO_DEBUGGER_IF_PRESENT 0
#endif

#ifndef JETBYTE_PURE_CALL_BREAK_INTO_DEBUGGER_IF_PRESENT
#define JETBYTE_PURE_CALL_BREAK_INTO_DEBUGGER_IF_PRESENT 0
#endif

#ifndef JETBYTE_PURE_CALL_HANG_ON_ERROR
#define JETBYTE_PURE_CALL_HANG_ON_ERROR 0
#endif

#ifndef JETBYTE_INTRUSIVE_RED_BLACK_TREE_DEBUG_TRACE
#define JETBYTE_INTRUSIVE_RED_BLACK_TREE_DEBUG_TRACE 0
#endif

#ifndef JETBYTE_INTRUSIVE_RED_BLACK_TREE_VALIDATE_ON_EVERY_OPERATION
#define JETBYTE_INTRUSIVE_RED_BLACK_TREE_VALIDATE_ON_EVERY_OPERATION 0
#endif

#ifndef JETBYTE_INTRUSIVE_RED_BLACK_TREE_INTERNAL_STATE_FAILURE_EXCEPTIONS
#define JETBYTE_INTRUSIVE_RED_BLACK_TREE_INTERNAL_STATE_FAILURE_EXCEPTIONS 0
#endif

#ifndef JETBYTE_INTRUSIVE_RED_BLACK_TREE_DUMP_TREE_ENABLED
#define JETBYTE_INTRUSIVE_RED_BLACK_TREE_DUMP_TREE_ENABLED 0
#endif

#ifndef JETBYTE_INTRUSIVE_RED_BLACK_TREE_DO_NOT_CLEANUP_ON_FAILED_VALIDATION
#define JETBYTE_INTRUSIVE_RED_BLACK_TREE_DO_NOT_CLEANUP_ON_FAILED_VALIDATION 0
#endif

#ifndef JETBYTE_INTRUSIVE_MULTI_MAP_INTERNAL_STATE_FAILURE_EXCEPTIONS
#define JETBYTE_INTRUSIVE_MULTI_MAP_INTERNAL_STATE_FAILURE_EXCEPTIONS 0
#endif

#ifndef JETBYTE_DUMP_NAMED_INDEX_DETAILS_ON_LOCK
#define JETBYTE_DUMP_NAMED_INDEX_DETAILS_ON_LOCK 0
#endif



#ifdef JETBYTE_ADMIN_ENABLE_ALL_THIRD_PARTY_CODE

#ifndef JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER
#define JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER 1
#endif

#else
#ifndef JETBYTE_ADMIN_ENABLE_THIRD_PARTY_CODE
#ifdef JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER
#if (JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER == 1)
#undef JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER
#define JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER 0
#endif
#endif
#endif
#endif

#ifndef JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER
#define JETBYTE_WIN32_THIRD_PARTY_CODE_ENABLE_STACKWALKER 0
#endif

///////////////////////////////////////////////////////////////////////////////
// End of file: Admin.h
///////////////////////////////////////////////////////////////////////////////
