#pragma once
///////////////////////////////////////////////////////////////////////////////
// File: Warnings.h
///////////////////////////////////////////////////////////////////////////////
//
// The code in this file is released under the The MIT License (MIT)
//
// Copyright (c) 2021 JetByte Limited.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the “Software”), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
///////////////////////////////////////////////////////////////////////////////

#include "JetByteTools/Admin/Platform.h"

#if defined(JETBYTE_TOOLS_ADMIN_WINDOWS_PLATFORM)
#include "JetByteTools/Admin/Platform/Windows/Warnings.h"
#endif

#ifndef SuppressNoSymbolsFoundWarning
#define SuppressNoSymbolsFoundWarning()
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_PUSH
#define JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_POP
#define JETBYTE_WARNING_SUPPRESS_POP
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_ENUM_VALUE_NOT_HANDLED_IN_SWITCH
#define JETBYTE_WARNING_SUPPRESS_ENUM_VALUE_NOT_HANDLED_IN_SWITCH JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_CAST_ALIGN
#define JETBYTE_WARNING_SUPPRESS_CAST_ALIGN JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_DTOR_THROWS
#define JETBYTE_WARNING_SUPPRESS_DTOR_THROWS JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_SIGN_OVERFLOW
#define JETBYTE_WARNING_SUPPRESS_SIGN_OVERFLOW JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_SIGNED_UNSIGNED_MISMATCH
#define JETBYTE_WARNING_SUPPRESS_SIGNED_UNSIGNED_MISMATCH JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_IMPLICIT_FALLTHROUGH
#define JETBYTE_WARNING_SUPPRESS_IMPLICIT_FALLTHROUGH JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_NOT_A_STRING_LITERAL
#define JETBYTE_WARNING_SUPPRESS_NOT_A_STRING_LITERAL JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_SELF_ASSIGN_OVERLOADED
#define JETBYTE_WARNING_SUPPRESS_SELF_ASSIGN_OVERLOADED JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_UNHANDLED_SWITCH_ENUM
#define JETBYTE_WARNING_SUPPRESS_UNHANDLED_SWITCH_ENUM JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_ENUM_VALUE_NOT_HANDLED_IN_SWITCH
#define JETBYTE_WARNING_SUPPRESS_ENUM_VALUE_NOT_HANDLED_IN_SWITCH JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_OVERLOADED_HIDDEN_VIRTUAL
#define JETBYTE_WARNING_SUPPRESS_OVERLOADED_HIDDEN_VIRTUAL JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_CLASS_MEM_ACCESS
#define JETBYTE_WARNING_SUPPRESS_CLASS_MEM_ACCESS JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_UNUSED_VARIABLE
#define JETBYTE_WARNING_SUPPRESS_UNUSED_VARIABLE JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_FORMAT_TRUNCATION
#define JETBYTE_WARNING_SUPPRESS_FORMAT_TRUNCATION JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_FORMAT_OVERFLOW
#define JETBYTE_WARNING_SUPPRESS_FORMAT_OVERFLOW JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_STRINGOP_OVERFLOW
#define JETBYTE_WARNING_SUPPRESS_STRINGOP_OVERFLOW JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_SUGGEST_OVERRIDE_DTOR
#define JETBYTE_WARNING_SUPPRESS_SUGGEST_OVERRIDE_DTOR JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_SUGGEST_OVERRIDE
#define JETBYTE_WARNING_SUPPRESS_SUGGEST_OVERRIDE JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_REINTERPRET_CAST_UNDEFINED_BEHAVIOR
#define JETBYTE_WARNING_SUPPRESS_REINTERPRET_CAST_UNDEFINED_BEHAVIOR JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_DONT_USE_C_STYLE_CASTS
#define JETBYTE_WARNING_SUPPRESS_DONT_USE_C_STYLE_CASTS JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_TYPE_QUALIFIERS_IGNORED
#define JETBYTE_WARNING_SUPPRESS_TYPE_QUALIFIERS_IGNORED JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_NULL_POINTER_ARITHMETIC
#define JETBYTE_WARNING_SUPPRESS_NULL_POINTER_ARITHMETIC JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_UNSAFE_POINTER_ARITHMETIC
#define JETBYTE_WARNING_SUPPRESS_UNSAFE_POINTER_ARITHMETIC JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_MISSING_SWITCH_DEFAULT_LABEL
#define JETBYTE_WARNING_SUPPRESS_MISSING_SWITCH_DEFAULT_LABEL JETBYTE_WARNING_SUPPRESS_PUSH
#endif

#ifndef JETBYTE_WARNING_SUPPRESS_STRICT_CAST_TO_FUNCTION_POINTER
#define JETBYTE_WARNING_SUPPRESS_STRICT_CAST_TO_FUNCTION_POINTER JETBYTE_WARNING_SUPPRESS_PUSH
#endif

// For C++ static lifetime safety analysis.
// See https://lemire.me/blog/2024/07/26/safer-code-in-c-with-lifetime-bounds/
// See https://clang.llvm.org/docs/LifetimeSafety.html

#ifndef JETBYTE_LIFETIME_BOUND_ANNOTATION
#define JETBYTE_LIFETIME_BOUND_ANNOTATION
#endif

///////////////////////////////////////////////////////////////////////////////
// End of file: Warnings.h
///////////////////////////////////////////////////////////////////////////////
